### ISSUE TITLE
Wrong buffer size in wiki

### ISSUE THREAD

**Issue by mandar1jn** [tresni/PoweredPortals#1]
The wiki mentions the maximum buffer size for transfer is 16 bytes. This is wrong. The maximum buffer size on older portals is 32 bytes and, on the trap team portal it's actually 64 although the buffer is only padded until 32. 16 bytes is actually disproven by the existance of the Query and Write commands

**Comment by tresni** [comment]
I've updated the wiki to indicate 32 bytes. All the examples were correct, just missed up dating the header.
